export const countries = [
  {
    id: 1,
    name_en: 'Brazil',
    name_ro: 'Brazilia',
    name_ru: 'Бразилия',
    capital_en: 'Brasília',
    capital_ro: 'Brasília',
    capital_ru: 'Бразилиа',
    area: '8.515.767 km²',
    population: '211.000.000',
  },
  {
    id: 2,
    name_en: 'Argentina',
    name_ro: 'Argentina',
    name_ru: 'Аргентина',
    capital_en: 'Buenos Aires',
    capital_ro: 'Buenos Aires',
    capital_ru: 'Буэнос-Айрес',
    area: '2.780.400 km²',
    population: '45.380.000',
  },
  {
    id: 3,
    name_en: 'Canada',
    name_ro: 'Canada',
    name_ru: 'Канада',
    capital_en: 'Ottawa',
    capital_ro: 'Ottawa',
    capital_ru: 'Оттава',
    area: '9.984.670 km²',
    population: '38.010.000',
  },
  {
    id: 4,
    name_en: 'China',
    name_ro: 'China',
    name_ru: 'Китай',
    capital_en: 'Beijing',
    capital_ro: 'Beijing',
    capital_ru: 'Пекин',
    area: '9.596.961 km²',
    population: '1.412.000.000',
  },
  {
    id: 5,
    name_en: 'India',
    name_ro: 'India',
    name_ru: 'Индия',
    capital_en: 'New Delhi',
    capital_ro: 'New Delhi',
    capital_ru: 'Нью-Дели',
    area: '3.287.263 km²',
    population: '1.408.000.000',
  },
  {
    id: 6,
    name_en: 'Australia',
    name_ro: 'Australia',
    name_ru: 'Австралия',
    capital_en: 'Canberra',
    capital_ro: 'Canberra',
    capital_ru: 'Канберра',
    area: '7.692.024 km²',
    population: '26.010.000',
  },
  {
    id: 7,
    name_en: 'United States',
    name_ro: 'Statele Unite',
    name_ru: 'США',
    capital_en: 'Washington, D.C.',
    capital_ro: 'Washington, D.C.',
    capital_ru: 'Вашингтон',
    area: '9.833.517 km²',
    population: '331.900.000',
  },
  {
    id: 8,
    name_en: 'Mexico',
    name_ro: 'Mexic',
    name_ru: 'Мексика',
    capital_en: 'Mexico City',
    capital_ro: 'Mexico City',
    capital_ru: 'Мехико',
    area: '1.964.375 km²',
    population: '126.700.000',
  },
  {
    id: 9,
    name_en: 'Indonesia',
    name_ro: 'Indonezia',
    name_ru: 'Индонезия',
    capital_en: 'Jakarta',
    capital_ro: 'Jakarta',
    capital_ru: 'Джакарта',
    area: '1.904.569 km²',
    population: '276.360.000',
  },
  {
    id: 10,
    name_en: 'South Africa',
    name_ro: 'Africa de Sud',
    name_ru: 'Южная Африка',
    capital_en: 'Pretoria',
    capital_ro: 'Pretoria',
    capital_ru: 'Претория',
    area: '1.221.037 km²',
    population: '60.140.000',
  },
  {
    id: 11,
    name_en: 'Nigeria',
    name_ro: 'Nigeria',
    name_ru: 'Нигерия',
    capital_en: 'Abuja',
    capital_ro: 'Abuja',
    capital_ru: 'Абуджа',
    area: '923.768 km²',
    population: '223.800.000',
  },
];
